### ISSUE TITLE
About https://github.com/hlky/k-diffusion-sd

### ISSUE THREAD

**Issue by Victor-Cooper** [hlky/laion-dreamstudio#2]
Hi. I got no where to find answer so I think this could be place that I can contact with you. I am installing stable diffusion and in this tutorial "https://github.com/darkhemic/stable-diffusion-cpuonly" I need to call 'pip install -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion'. However looks like the repo has been removed. I am wondering whether there is a replacement for it? Thanks!

**Comment by hlky** [comment]
The fork of k-diffusion was required for a time last year when k-diffusion did not have the correct setup files and was not available on pypi.
The repository you are attempting to use has not been updated since the same time. I would recommend using a different UI that supports using CPU only.
